version: "3"
services:
  app:
    container_name: mock
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn --reload --bind 0.0.0.0:5000 "app:create_app()"
    volumes:
      - ./app:/project
    ports:
      - 5000:5000
