version: "3"
services:
  app:
    container_name: mock
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --reload --bind 0.0.0.0:5000 "mock:app"
    volumes:
      - .:/project
    ports:
      - 5000:5000
